version: '3.8'

services:
  postgres:
    build:
      context: ./postgres  
      dockerfile: Dockerfile  
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/.env  
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  pg_data:

networks:
  app_network:
