# Generated by Django 4.2.16 on 2024-11-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='fitness_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(),
        ),
    ]
