# Generated by Django 4.2.16 on 2024-11-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_age_alter_user_fitness_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('force', models.CharField(blank=True, choices=[(None, 'None'), ('static', 'Static'), ('pull', 'Pull'), ('push', 'Push')], max_length=10, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=15)),
                ('mechanic', models.CharField(blank=True, choices=[(None, 'None'), ('isolation', 'Isolation'), ('compound', 'Compound')], max_length=15, null=True)),
                ('equipment', models.CharField(blank=True, choices=[(None, 'None'), ('medicine ball', 'Medicine Ball'), ('dumbbell', 'Dumbbell'), ('body only', 'Body Only'), ('bands', 'Bands'), ('kettlebells', 'Kettlebells'), ('foam roll', 'Foam Roll'), ('cable', 'Cable'), ('machine', 'Machine'), ('barbell', 'Barbell'), ('exercise ball', 'Exercise Ball'), ('e-z curl bar', 'E-Z Curl Bar'), ('other', 'Other')], max_length=20, null=True)),
                ('primary_muscles', models.JSONField()),
                ('secondary_muscles', models.JSONField()),
                ('instructions', models.JSONField()),
                ('category', models.CharField(choices=[('powerlifting', 'Powerlifting'), ('strength', 'Strength'), ('stretching', 'Stretching'), ('cardio', 'Cardio'), ('olympic weightlifting', 'Olympic Weightlifting'), ('strongman', 'Strongman'), ('plyometrics', 'Plyometrics')], max_length=50)),
                ('images', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
