# Generated by Django 4.2.16 on 2024-11-22 18:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_exercise_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_date', models.DateField()),
                ('workout_time', models.TimeField()),
                ('sets', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, help_text='Array of objects with set details (set number, reps, weight)', size=None)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exercise')),
                ('user_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
